Revert "Scicos OCaml part: generated bytecode executables"
Fails to compile under some platforms using clang:
Error: Files src/xml2modelica/xMLParser.cmx and src/xml2modelica/linenum.cmx
       make inconsistent assumptions over interface Linenum

This reverts commit 3ac381e3feb30edd39955b8b217e4fe9c2792b95.

Change-Id: I54a1203ef800c664a92f8a2fdb26addaca429312